language: node_js
node_js:
  - "0.8"
  - "0.12"
  - "io.js"
matrix:
  include:
    - node_js: "0.10"
      env: BROWSER=true
before_install:
  - npm install -g npm
  - npm install -g karma-cli
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm test
  - "[ $BROWSER == false ] || npm run test-browser"
  # Karma sauce is limited to running about 5-7 browsers (or it will tiemout) at a time so we just run vendor by vendor here
  - "[ $BROWSER == false ] || karma start karma.conf-sauce.js --browsers FIREFOX_V4,FIREFOX_V11,FIREFOX_V20,FIREFOX_V30,FIREFOX_V35"
  - "[ $BROWSER == false ] || karma start karma.conf-sauce.js --browsers CHROME_V28,CHROME_V35,CHROME_V40,ANDROID_V4.0,ANDROID_V4.3"
  - "[ $BROWSER == false ] || karma start karma.conf-sauce.js --browsers INTERNET_EXPLORER_V9,INTERNET_EXPLORER_V10,INTERNET_EXPLORER_V11"
  - "[ $BROWSER == false ] || karma start karma.conf-sauce.js --browsers SAFARI_V5,SAFARI_V6,SAFARI_V7"
  - "[ $BROWSER == false ] || karma start karma.conf-sauce.js --browsers OPERA_V11,OPERA_V12"
notifications:
  email: false
env:
  global:
  - secure: HNxvir0JZPu3aES+e5hLrSf0qRCmvAbxUFw/F8fBpPSrhOMQcLcz/4PwNZtCitlzgvYHgnOuGNPiRyBjD7KyOInDz9TAoFEy26b6DW21DrdBXszFpa6seD800zkbfo3SkiTBArBMnkFxjY/34nSkt8FLbucASD98CYZFPF5Ry1M=
  - secure: JHs03agkHAAhhIca/+xw2iIJZwsgGwFx0i1e0uTeofhBEulY49MeX06tPlHr83BoYUtJj0OS9HY3VT/JHq1DhswXzxx2FAaFf63iIbQPVBMGKyd8Vy5dua6LHpbl39Aeq93BqY38d4AoKWwzrLc/FbRxzSKuQo1BqfL8aKSrLY4=
  matrix: BROWSER=false 